#!/usr/bin/env python3
"""Rename bundled font metadata, preserving glyphs and upstream license records.

Requires the existing fontTools Python package. Node's built-in Brotli is a
fallback when the optional Python Brotli extension is absent. The offline page
contains a generated byte-identical inline copy, refreshed with the font.
"""
import base64
import re
import subprocess
import sys
import types
from pathlib import Path

try:
    import brotli
except ImportError:
    def codec(data, operation):
        js = (
            'const z=require("node:zlib");const a=[];'
            'process.stdin.on("data",d=>a.push(d));'
            'process.stdin.on("end",()=>process.stdout.write('
            f'z.{operation}(Buffer.concat(a))));'
        )
        return subprocess.run(
            ["node", "-e", js], input=data, stdout=subprocess.PIPE, check=True
        ).stdout

    sys.modules["brotli"] = types.SimpleNamespace(
        MODE_FONT=2,
        decompress=lambda data: codec(data, "brotliDecompressSync"),
        compress=lambda data, **kwargs: codec(data, "brotliCompressSync"),
    )

from fontTools.ttLib import TTFont

web = Path(__file__).resolve().parent.parent
path = web / "src/assets/fonts/yaran-blocks.woff2"
font = TTFont(path)
changed = False
for record in font["name"].names:
    if record.nameID not in (1, 3, 4, 6):
        continue
    before = record.toUnicode()
    after = before.replace("Dux Blocks", "Yaran Blocks").replace("DuxBlocks", "YaranBlocks")
    if before != after:
        record.string = after.encode(record.getEncoding())
        changed = True
if changed:
    font.save(path)
font.close()

page = web / "public/offline.html"
source = page.read_text()
encoded = base64.b64encode(path.read_bytes()).decode()
updated, count = re.subn(
    r"(?<=url\(data:font/woff2;base64,)[A-Za-z0-9+/=]+(?=\))", encoded, source
)
if count != 1:
    raise RuntimeError(f"Expected one offline font embed, found {count}")
page.write_text(updated)
print("Verified Yaran Blocks metadata and refreshed offline font embed")
